os: linux
services:
   - docker
sudo: required
language: python

branches:
  except:
  - appveyor-test
  - /.*no-ci.*/

env:
  matrix:
    - DOCKER_IMAGE=lasote/conanclang60
      CC=clang
      CXX=clang++
      ASAN=1
    - DOCKER_IMAGE=lasote/conanclang60
      CC=clang
      CXX=clang++
    - DOCKER_IMAGE=lasote/conanclang50
      CC=clang
      CXX=clang++
    - DOCKER_IMAGE=lasote/conanclang40
      CC=clang
      CXX=clang++
    - DOCKER_IMAGE=lasote/conanclang39
      CC=clang
      CXX=clang++
    - DOCKER_IMAGE=lasote/conanclang38
      CC=clang
      CXX=clang++
    - DOCKER_IMAGE=lasote/conangcc8
      CC=gcc
      CXX=g++
    - DOCKER_IMAGE=lasote/conangcc7
      CC=gcc
      CXX=g++
    - DOCKER_IMAGE=lasote/conangcc6
      CC=gcc
      CXX=g++
    - DOCKER_IMAGE=lasote/conangcc5
      CC=gcc
      CXX=g++

script:
  docker run -v$(pwd):/home/conan $DOCKER_IMAGE bash -c "CC=${CC} CXX=${CXX} ASAN=${ASAN} .travis/build_project.sh"
