os: linux
services:
   - docker
sudo: required
language: python

branches:
  except:
  - appveyor-test
  - /.*no-ci.*/

env:
  matrix:
    - DOCKER_IMAGE=conanio/clang7
      CC=clang
      CXX=clang++
      ASAN=1
    - DOCKER_IMAGE=conanio/clang7
      CC=clang
      CXX=clang++
    - DOCKER_IMAGE=conanio/gcc8
      CC=gcc
      CXX=g++

script:
  docker run -v$(pwd):/home/conan $DOCKER_IMAGE bash -c "CC=${CC} CXX=${CXX} ASAN=${ASAN} .travis/build_project.sh"
